import type { Gender, Product } from "@/lib/types";

/**
 * Static catalog for the Your Fashionista storefront.
 * Images live in /public/products and are served by Next.js from there.
 */
export const PRODUCTS: Product[] = [
  /* ---------------------------------------------------------------- women */
  {
    id: "w-01",
    slug: "meadow-floral-midi-dress",
    name: "Meadow Floral Midi Dress",
    gender: "women",
    category: "dresses",
    price: 89,
    compareAtPrice: 110,
    image: "/products/w-dress-floral.jpg",
    imageAlt: "Woman wearing a flowing floral sundress outdoors",
    colors: [
      { name: "Sage", hex: "#8a9a7b" },
      { name: "Blush", hex: "#e6c7c1" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A floaty midi cut from featherlight viscose, printed with a soft meadow floral that moves beautifully from beach days to garden parties.",
    details: [
      "100% viscose, woven finish",
      "Midi length with a relaxed A-line skirt",
      "Adjustable shoulder ties and side pockets",
    ],
    rating: 4.7,
    reviews: 128,
    rank: 6,
  },
  {
    id: "w-02",
    slug: "sienna-kaftan-maxi-dress",
    name: "Sienna Kaftan Maxi Dress",
    gender: "women",
    category: "dresses",
    price: 124,
    image: "/products/w-dress-kaftan.jpg",
    imageAlt: "Flowing patterned kaftan maxi dress",
    colors: [
      { name: "Rust", hex: "#b45a3c" },
      { name: "Sand", hex: "#d9c3a3" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "An easy kaftan silhouette in a bold geometric print — the one you reach for when the temperature climbs and you still want to look considered.",
    details: [
      "Lightweight crepe with a soft drape",
      "Pull-on styling with a V neckline",
      "Falls to the ankle, works over swimwear",
    ],
    rating: 4.6,
    reviews: 74,
    isNew: true,
    rank: 20,
  },
  {
    id: "w-03",
    slug: "scarlet-wrap-midi-dress",
    name: "Scarlet Wrap Midi Dress",
    gender: "women",
    category: "dresses",
    price: 98,
    image: "/products/w-dress-wrap.jpg",
    imageAlt: "Woman in a colourful wrap dress standing on a city street",
    colors: [
      { name: "Scarlet", hex: "#c2413a" },
      { name: "Black", hex: "#1c1b18" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "Our best-selling wrap dress, reissued in a saturated print. The tie waist and swishy skirt make it the most-worn piece in our studio.",
    details: [
      "Polyester satin with a matte hand-feel",
      "True wrap closure with inner tie",
      "Midi length, 112 cm from shoulder (size S)",
    ],
    rating: 4.8,
    reviews: 212,
    rank: 3,
  },
  {
    id: "w-04",
    slug: "dot-pleated-midi-skirt",
    name: "Dot Pleated Midi Skirt",
    gender: "women",
    category: "skirts",
    price: 69,
    image: "/products/w-skirt-polka.jpg",
    imageAlt: "Woman wearing a red polka-dot midi skirt and white tank top",
    colors: [
      { name: "Cherry", hex: "#c2413a" },
      { name: "Cream", hex: "#efe9df" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "Sun-ready pleats scattered with micro dots, cut to hit mid-calf so it pairs as easily with trainers as with a heeled sandal.",
    details: [
      "Satin-touch polyester with knife pleats",
      "Hidden elasticated waistband",
      "Fully lined for opaque coverage",
    ],
    rating: 4.5,
    reviews: 63,
    rank: 27,
  },
  {
    id: "w-05",
    slug: "feather-print-wrap-skirt",
    name: "Feather-Print Wrap Skirt",
    gender: "women",
    category: "skirts",
    price: 74,
    image: "/products/w-skirt-feather.jpg",
    imageAlt: "Black wrap skirt with a colourful feather print worn with white sneakers",
    colors: [
      { name: "Ink", hex: "#2d2b26" },
      { name: "Ivory", hex: "#f2ede4" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A true wrap skirt with a graphic feather print and a curved hem that shows a little ankle when you walk.",
    details: [
      "Cotton-twill with a brushed finish",
      "Side tie fastening, adjustable fit",
      "Mini-to-midi length, 78 cm",
    ],
    rating: 4.4,
    reviews: 41,
    isNew: true,
    rank: 31,
  },
  {
    id: "w-06",
    slug: "camel-wool-blend-coat",
    name: "Camel Wool-Blend Coat",
    gender: "women",
    category: "outerwear",
    price: 189,
    compareAtPrice: 240,
    image: "/products/w-coat-tan.jpg",
    imageAlt: "Woman wearing a camel tan coat on a city sidewalk",
    colors: [
      { name: "Camel", hex: "#c39b6a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A wrap coat in a wool-cashmere blend with a wide lapel and a belt that cinches over everything from knitwear to a slip dress.",
    details: [
      "70% wool, 20% poly, 10% cashmere",
      "Relaxed shoulder with a longline cut",
      "Dry clean only",
    ],
    rating: 4.9,
    reviews: 96,
    rank: 4,
  },
  {
    id: "w-07",
    slug: "belted-notch-lapel-coat",
    name: "Belted Notch-Lapel Coat",
    gender: "women",
    category: "outerwear",
    price: 205,
    image: "/products/w-coat-notch.jpg",
    imageAlt: "Woman in a brown notched lapel coat",
    colors: [
      { name: "Taupe", hex: "#a8977f" },
      { name: "Black", hex: "#23211e" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "Sharp tailoring in a heavyweight wool blend — a notched lapel, welt pockets and a self belt give it a polished, quiet-luxury line.",
    details: [
      "Double-faced wool blend",
      "Concealed button placket",
      "Interior pocket and satin lining",
    ],
    rating: 4.7,
    reviews: 58,
    rank: 14,
  },
  {
    id: "w-08",
    slug: "tailored-double-breasted-blazer",
    name: "Tailored Double-Breasted Blazer",
    gender: "women",
    category: "outerwear",
    price: 149,
    image: "/products/w-blazer-black.jpg",
    imageAlt: "Woman in a black tailored blazer and monochrome skirt",
    colors: [
      { name: "Black", hex: "#1c1b18" },
      { name: "Ivory", hex: "#efe9df" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "The blazer that pulls an outfit together: slightly oversized through the body, with a strong shoulder and horn-effect buttons.",
    details: [
      "Stretch suiting with a fluid drape",
      "Double-breasted front, two flap pockets",
      "Wear it buttoned as a dress or over denim",
    ],
    rating: 4.6,
    reviews: 87,
    isNew: true,
    rank: 9,
  },
  {
    id: "w-09",
    slug: "structured-leather-satchel",
    name: "Structured Leather Satchel",
    gender: "women",
    category: "bags",
    price: 139,
    image: "/products/w-bag-satchel.jpg",
    imageAlt: "Grey leather satchel bag with gold buckles",
    colors: [
      { name: "Stone", hex: "#8d8a80" },
      { name: "Tan", hex: "#c39b6a" },
    ],
    sizes: ["One Size"],
    description:
      "A compact satchel in pebbled leather with brushed-gold hardware, sized for a 13-inch laptop and everything that rides along with it.",
    details: [
      "Pebbled cowhide leather",
      "Detachable shoulder strap",
      "Zip top with two slip pockets inside",
    ],
    rating: 4.7,
    reviews: 45,
    rank: 24,
  },
  {
    id: "w-10",
    slug: "everyday-leather-tote",
    name: "Everyday Leather Tote",
    gender: "women",
    category: "bags",
    price: 159,
    image: "/products/w-bag-leather.jpg",
    imageAlt: "Black leather tote bag on a bright background",
    colors: [
      { name: "Black", hex: "#171614" },
      { name: "Cognac", hex: "#8a5a33" },
    ],
    sizes: ["One Size"],
    description:
      "A soft, unstructured tote that swallows a day's worth of life — plus a magnetic closure so nothing tumbles out on the train.",
    details: [
      "Smooth full-grain leather",
      "Fits a 15-inch laptop",
      "Magnetic flap closure with key clip",
    ],
    rating: 4.8,
    reviews: 133,
    rank: 16,
  },
  {
    id: "w-11",
    slug: "floral-almond-toe-pumps",
    name: "Floral Almond-Toe Pumps",
    gender: "women",
    category: "shoes",
    price: 112,
    image: "/products/w-heels-floral.jpg",
    imageAlt: "Pair of blue and pink floral almond-toe heeled pumps",
    colors: [
      { name: "Multi", hex: "#b45a3c" },
      { name: "Navy", hex: "#2f3b52" },
    ],
    sizes: ["36", "37", "38", "39", "40", "41"],
    description:
      "A printed pump on a walkable 6 cm heel — the finishing note for tailoring, denim and every wedding invitation in between.",
    details: [
      "Textile upper with a pointed almond toe",
      "6 cm stiletto heel, lightly padded sock",
      "Leather-look sole with grip inserts",
    ],
    rating: 4.3,
    reviews: 37,
    rank: 33,
  },
  {
    id: "w-12",
    slug: "textured-pointed-pumps",
    name: "Textured Pointed Pumps",
    gender: "women",
    category: "shoes",
    price: 128,
    compareAtPrice: 160,
    image: "/products/w-heels-white.jpg",
    imageAlt: "Pair of white textured high-heeled pumps",
    colors: [
      { name: "White", hex: "#f4f2ee" },
      { name: "Black", hex: "#1c1b18" },
    ],
    sizes: ["36", "37", "38", "39", "40", "41"],
    description:
      "A textured pump with a slim 7 cm heel and a sharply pointed toe, finished with a leather-effect lining for all-day comfort.",
    details: [
      "Woven-effect upper",
      "7 cm heel with cushioned insole",
      "True to size",
    ],
    rating: 4.6,
    reviews: 72,
    rank: 26,
  },
  {
    id: "w-13",
    slug: "ribbed-knit-sweater",
    name: "Ribbed Knit Sweater",
    gender: "women",
    category: "knitwear",
    price: 79,
    compareAtPrice: 95,
    image: "/products/w-knit-grey.jpg",
    imageAlt: "Person wearing a grey ribbed knit sweater",
    colors: [
      { name: "Grey", hex: "#a9a7a1" },
      { name: "Cream", hex: "#efe9df" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A fine-gauge rib knit with a slim sleeve and a relaxed body — warm enough for January, light enough to layer under a blazer.",
    details: [
      "Merino-blend yarn with stretch",
      "Ribbed crew neck, cuffs and hem",
      "Machine wash cold on a delicate cycle",
    ],
    rating: 4.7,
    reviews: 156,
    rank: 10,
  },
  {
    id: "w-14",
    slug: "soft-crew-knit-jumper",
    name: "Soft Crew Knit Jumper",
    gender: "women",
    category: "knitwear",
    price: 84,
    image: "/products/w-knit-red.jpg",
    imageAlt: "Woman in a red crew neck knit sweater",
    colors: [
      { name: "Cherry", hex: "#b3352f" },
      { name: "Oat", hex: "#d9cbb3" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A cheerful crew neck in a brushed knit that feels like a hug — the easiest way to make jeans and boots look intentional.",
    details: [
      "Acrylic-wool blend, brushed finish",
      "Dropped shoulder, hip-length hem",
      "Hand wash or wool cycle",
    ],
    rating: 4.6,
    reviews: 68,
    isNew: true,
    rank: 18,
  },
  {
    id: "w-15",
    slug: "relaxed-straight-jeans",
    name: "Relaxed Straight Jeans",
    gender: "women",
    category: "denim",
    price: 92,
    image: "/products/w-jeans-straight.jpg",
    imageAlt: "Woman standing in relaxed straight-leg jeans and a white top",
    colors: [
      { name: "Indigo", hex: "#3f5a7a" },
      { name: "Wash", hex: "#7d96b3" },
    ],
    sizes: ["24", "26", "28", "30", "32"],
    description:
      "A high-rise straight leg in rigid-look stretch denim — the fit our customers re-order in a second wash within a month.",
    details: [
      "99% cotton, 1% elastane",
      "High rise, straight leg, ankle crop",
      "Five-pocket construction",
    ],
    rating: 4.8,
    reviews: 241,
    rank: 5,
  },
  {
    id: "w-16",
    slug: "high-rise-slim-jeans",
    name: "High-Rise Slim Jeans",
    gender: "women",
    category: "denim",
    price: 88,
    image: "/products/w-jeans-blue.jpg",
    imageAlt: "Person wearing blue high-rise slim jeans",
    colors: [
      { name: "Mid Blue", hex: "#5a7ea6" },
      { name: "Black", hex: "#23211e" },
    ],
    sizes: ["24", "26", "28", "30", "32"],
    description:
      "A slim leg with room through the thigh and a high waist that stays put, washed to a clean mid-blue with subtle fading.",
    details: [
      "Stretch cotton denim, 280 gsm",
      "Zip fly with a button closure",
      "Sits at the natural waist",
    ],
    rating: 4.7,
    reviews: 187,
    rank: 7,
  },
  {
    id: "w-17",
    slug: "satin-tie-neck-blouse",
    name: "Satin Tie-Neck Blouse",
    gender: "women",
    category: "tops",
    price: 72,
    image: "/products/w-top-blouse-red.jpg",
    imageAlt: "Woman wearing a red blouse with a necklace",
    colors: [
      { name: "Crimson", hex: "#b3352f" },
      { name: "Cream", hex: "#efe9df" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A fluid satin blouse with a tie neckline that can be knotted loose or pulled tight, with cuffs that look just as good rolled up.",
    details: [
      "Recycled satin with a soft sheen",
      "Concealed button placket",
      "Pairs with the Tailored Black Blazer",
    ],
    rating: 4.5,
    reviews: 59,
    rank: 25,
  },
  {
    id: "w-18",
    slug: "essential-cotton-tee",
    name: "Essential Cotton Tee",
    gender: "women",
    category: "tops",
    price: 34,
    image: "/products/w-top-tee-white.jpg",
    imageAlt: "Plain white crew neck cotton t-shirt",
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Black", hex: "#1c1b18" },
      { name: "Grey", hex: "#b3b0a7" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "The white tee, perfected: mid-weight organic cotton with a neckline that holds its shape wash after wash.",
    details: [
      "100% organic cotton, 180 gsm",
      "Regular fit, not too boxy",
      "Pre-shrunk",
    ],
    rating: 4.6,
    reviews: 402,
    rank: 17,
  },

  /* ------------------------------------------------------------------ men */
  {
    id: "m-01",
    slug: "oxford-button-down-shirt",
    name: "Oxford Button-Down Shirt",
    gender: "men",
    category: "shirts",
    price: 78,
    image: "/products/m-shirt-oxford.jpg",
    imageAlt: "Blue Oxford button-down shirt laid flat",
    colors: [
      { name: "Sky", hex: "#a8c0d6" },
      { name: "White", hex: "#f7f6f3" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A genuine Oxford weave with a button-down collar and a slightly curved hem — dress it up with chinos, down with denim.",
    details: [
      "100% cotton Oxford cloth",
      "Regular fit with a single back pleat",
      "Machine washable, warm iron",
    ],
    rating: 4.7,
    reviews: 164,
    rank: 11,
  },
  {
    id: "m-02",
    slug: "classic-poplin-dress-shirt",
    name: "Classic Poplin Dress Shirt",
    gender: "men",
    category: "shirts",
    price: 69,
    compareAtPrice: 85,
    image: "/products/m-shirt-white.jpg",
    imageAlt: "Man wearing a crisp white dress shirt",
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Blue", hex: "#b9cfe0" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Crisp two-ply poplin with a clean spread collar — the shirt that keeps its shape from the first meeting to the last train.",
    details: [
      "100% cotton poplin, 120 thread count",
      "Slim fit through the body",
      "Non-iron finish",
    ],
    rating: 4.6,
    reviews: 121,
    rank: 13,
  },
  {
    id: "m-03",
    slug: "heavyweight-cotton-tee",
    name: "Heavyweight Cotton Tee",
    gender: "men",
    category: "tshirts",
    price: 32,
    image: "/products/m-tee-essential.jpg",
    imageAlt: "White heavyweight crew neck t-shirt on a hanger",
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Black", hex: "#1c1b18" },
      { name: "Stone", hex: "#c7c1b6" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A 240 gsm cotton tee with a structured collar and a boxy fit that holds its shape — the base layer everything else is built on.",
    details: [
      "100% combed cotton, 240 gsm",
      "Boxy fit, drop shoulder",
      "Reinforced neckline",
    ],
    rating: 4.8,
    reviews: 318,
    rank: 2,
  },
  {
    id: "m-04",
    slug: "everyday-crew-neck-tee",
    name: "Everyday Crew Neck Tee",
    gender: "men",
    category: "tshirts",
    price: 36,
    image: "/products/m-tee-heavy.jpg",
    imageAlt: "Man wearing a white crew neck t-shirt",
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Ecru", hex: "#e8e1d3" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Our softest crew: a washed mid-weight jersey that drapes cleanly and only gets better with wear.",
    details: [
      "Garment-dyed cotton jersey",
      "Regular fit, sits at the hip",
      "Resists twisting after washing",
    ],
    rating: 4.6,
    reviews: 142,
    rank: 19,
  },
  {
    id: "m-05",
    slug: "fleece-back-hoodie",
    name: "Fleece-Back Hoodie",
    gender: "men",
    category: "hoodies",
    price: 79,
    image: "/products/m-hoodie-black.jpg",
    imageAlt: "Man wearing a black fleece-back hoodie",
    colors: [
      { name: "Black", hex: "#1c1b18" },
      { name: "Heather", hex: "#a9a7a1" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A heavy fleece-back hoodie with a double-layer hood and a kangaroo pocket — cold-weather uniform, sorted.",
    details: [
      "80% cotton, 20% polyester, brushed fleece",
      "Relaxed fit with ribbed cuffs",
      "Flat drawcords with metal tips",
    ],
    rating: 4.7,
    reviews: 206,
    isNew: true,
    rank: 12,
  },
  {
    id: "m-06",
    slug: "loopback-cotton-hoodie",
    name: "Loopback Cotton Hoodie",
    gender: "men",
    category: "hoodies",
    price: 74,
    compareAtPrice: 90,
    image: "/products/m-hoodie-white.jpg",
    imageAlt: "Man in a white pullover hoodie on a road",
    colors: [
      { name: "Off White", hex: "#f1ede5" },
      { name: "Sand", hex: "#d9cbb3" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Loopback jersey gives this hoodie structure without weight, so it layers under a coat without the bulk.",
    details: [
      "100% loopback cotton, 400 gsm",
      "Regular fit",
      "Machine washable at 30°",
    ],
    rating: 4.5,
    reviews: 97,
    rank: 29,
  },
  {
    id: "m-07",
    slug: "cafe-racer-leather-jacket",
    name: "Café Racer Leather Jacket",
    gender: "men",
    category: "outerwear",
    price: 249,
    image: "/products/m-jacket-leather.jpg",
    imageAlt: "Man in a brown leather jacket wearing sunglasses",
    colors: [
      { name: "Tobacco", hex: "#8a5a33" },
      { name: "Black", hex: "#171614" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A minimal racer in supple lambskin with a stand collar and asymmetrical zip — a jacket you'll still be wearing in ten years.",
    details: [
      "Genuine lambskin leather",
      "Two-way zip with snap storm flap",
      "Satin lining with two inner pockets",
    ],
    rating: 4.9,
    reviews: 64,
    rank: 1,
  },
  {
    id: "m-08",
    slug: "washed-denim-jacket",
    name: "Washed Denim Jacket",
    gender: "men",
    category: "denim",
    price: 118,
    image: "/products/m-jacket-denim.jpg",
    imageAlt: "Man modelling a washed denim jacket",
    colors: [
      { name: "Mid Wash", hex: "#6f8bab" },
      { name: "Dark Wash", hex: "#38495e" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A trucker jacket with a lived-in wash and just enough stretch to throw over a hoodie without feeling boxed in.",
    details: [
      "98% cotton, 2% elastane denim",
      "Button front with chest flap pockets",
      "Ages with wear",
    ],
    rating: 4.7,
    reviews: 152,
    rank: 21,
  },
  {
    id: "m-09",
    slug: "tailored-navy-suit",
    name: "Tailored Navy Suit",
    gender: "men",
    category: "tailoring",
    price: 389,
    image: "/products/m-suit-navy.jpg",
    imageAlt: "Man in a blue tailored suit standing on a sidewalk",
    colors: [
      { name: "Navy", hex: "#2f3b52" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A half-canvassed two-piece in Italian wool with a soft shoulder — equally right at a wedding or a boardroom.",
    details: [
      "100% Super 110s wool",
      "Two-button jacket, flat-front trousers",
      "Unfinished trouser hem for tailoring",
    ],
    rating: 4.8,
    reviews: 91,
    rank: 8,
  },
  {
    id: "m-10",
    slug: "modern-fit-black-suit",
    name: "Modern Fit Black Suit",
    gender: "men",
    category: "tailoring",
    price: 410,
    image: "/products/m-suit-black.jpg",
    imageAlt: "Man in a black suit jacket and black trousers",
    colors: [{ name: "Black", hex: "#171614" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A sharp black suit cut close through the waist, with a subtle sheen that photographs beautifully after dark.",
    details: [
      "Wool-blend with a fine twill weave",
      "Notch lapel, single back vent",
      "Jacket and trousers sold together",
    ],
    rating: 4.8,
    reviews: 88,
    isNew: true,
    rank: 23,
  },
  {
    id: "m-11",
    slug: "merino-wool-crew-sweater",
    name: "Merino Wool Crew Sweater",
    gender: "men",
    category: "knitwear",
    price: 95,
    image: "/products/m-knit-merino.jpg",
    imageAlt: "Man wearing a dark merino crew neck sweater",
    colors: [
      { name: "Charcoal", hex: "#3a3a38" },
      { name: "Navy", hex: "#2f3b52" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Fine-gauge merino that regulates temperature and never feels scratchy — the knit that works with a shirt underneath or on its own.",
    details: [
      "100% extra-fine merino wool",
      "Slim fit, ribbed trims",
      "Naturally odour resistant",
    ],
    rating: 4.8,
    reviews: 119,
    rank: 15,
  },
  {
    id: "m-12",
    slug: "lambswool-crew-jumper",
    name: "Lambswool Crew Jumper",
    gender: "men",
    category: "knitwear",
    price: 89,
    compareAtPrice: 110,
    image: "/products/m-knit-red.jpg",
    imageAlt: "Man in a red lambswool crew jumper with black trousers",
    colors: [
      { name: "Brick", hex: "#a34a3a" },
      { name: "Forest", hex: "#3f5a44" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "A lambswool crew in a rich, saturated hue — the colour lift an all-neutral winter wardrobe needs.",
    details: [
      "100% lambswool",
      "Regular fit with a ribbed crew neck",
      "Hand wash cool, dry flat",
    ],
    rating: 4.6,
    reviews: 73,
    rank: 28,
  },
  {
    id: "m-13",
    slug: "slim-tapered-jeans",
    name: "Slim Tapered Jeans",
    gender: "men",
    category: "denim",
    price: 95,
    image: "/products/m-jeans-slim.jpg",
    imageAlt: "Blue denim jeans hanging on a wooden hanger",
    colors: [
      { name: "Indigo", hex: "#3f5a7a" },
      { name: "Black", hex: "#23211e" },
    ],
    sizes: ["28", "30", "32", "34", "36"],
    description:
      "A slim leg that tapers from the knee with a mid rise — clean through the seat with just enough stretch for the commute.",
    details: [
      "98% cotton, 2% elastane",
      "Mid rise, tapered leg",
      "Button fly with a zip",
    ],
    rating: 4.7,
    reviews: 233,
    rank: 22,
  },
  {
    id: "m-14",
    slug: "tailored-chino-trousers",
    name: "Tailored Chino Trousers",
    gender: "men",
    category: "trousers",
    price: 72,
    image: "/products/m-chino.jpg",
    imageAlt: "Man wearing tailored brown chino trousers and sneakers",
    colors: [
      { name: "Stone", hex: "#c7bda9" },
      { name: "Olive", hex: "#5f6a4a" },
      { name: "Navy", hex: "#2f3b52" },
    ],
    sizes: ["28", "30", "32", "34", "36"],
    description:
      "A clean-front chino with a tapered leg and a hint of stretch — the trousers that work in the office and at the weekend.",
    details: [
      "Cotton-stretch twill",
      "Flat front with a hidden comfort waistband",
      "Unfinished hem for a custom break",
    ],
    rating: 4.6,
    reviews: 174,
    rank: 30,
  },
  {
    id: "m-15",
    slug: "court-low-sneakers",
    name: "Court Low Sneakers",
    gender: "men",
    category: "shoes",
    price: 110,
    image: "/products/m-sneaker-low.jpg",
    imageAlt: "Low-top court sneakers worn on a ledge",
    colors: [
      { name: "White/Green", hex: "#e8e1d3" },
      { name: "White/Red", hex: "#f7f6f3" },
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    description:
      "A low-profile court sneaker in smooth leather with a cushioned footbed — clean enough for tailoring, easy enough for denim.",
    details: [
      "Leather upper with a rubber cupsole",
      "Padded collar and cushioned insole",
      "Runs true to size",
    ],
    rating: 4.7,
    reviews: 268,
    rank: 32,
  },
  {
    id: "m-16",
    slug: "heritage-high-top-sneakers",
    name: "Heritage High-Top Sneakers",
    gender: "men",
    category: "shoes",
    price: 125,
    image: "/products/m-sneaker-high.jpg",
    imageAlt: "Pair of white high-top sneakers",
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Black", hex: "#1c1b18" },
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    description:
      "A padded high-top with a vulcanised sole and a cushioned ankle — the silhouette that never dates.",
    details: [
      "Canvas and leather upper",
      "Vulcanised rubber sole",
      "Lace-up with a padded collar",
    ],
    rating: 4.8,
    reviews: 143,
    isNew: true,
    rank: 34,
  },
  {
    id: "m-17",
    slug: "retro-runner-trainers",
    name: "Retro Runner Trainers",
    gender: "men",
    category: "shoes",
    price: 99,
    compareAtPrice: 129,
    image: "/products/m-sneaker-runner.jpg",
    imageAlt: "Pair of white and orange retro runner trainers",
    colors: [
      { name: "White/Orange", hex: "#e8e1d3" },
      { name: "Grey", hex: "#b3b0a7" },
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    description:
      "A '90s-inspired runner with a suede overlay and a chunky midsole that absorbs every step of a long city day.",
    details: [
      "Suede and mesh upper",
      "EVA midsole with a treaded outsole",
      "Removable footbed",
    ],
    rating: 4.5,
    reviews: 91,
    rank: 35,
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  dresses: "Dresses",
  tops: "Tops & T-Shirts",
  tshirts: "T-Shirts",
  knitwear: "Knitwear",
  denim: "Denim",
  skirts: "Skirts",
  outerwear: "Outerwear",
  tailoring: "Tailoring",
  trousers: "Trousers",
  hoodies: "Hoodies",
  shirts: "Shirts",
  shoes: "Footwear",
  bags: "Bags",
};

export function categoryLabel(slug: string): string {
  return CATEGORY_LABELS[slug] ?? slug;
}
